//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenivoNetwork.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int ID { get; set; }
        public int FirstUserID { get; set; }
        public int SecondUserID { get; set; }
        public bool IsAccepted { get; set; }
    
        public virtual User FirstUser { get; set; }
        public virtual User SecondUser { get; set; }
    }
}
